---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helpdesk-service
  namespace: enterprise-observability
  labels:
    app: helpdesk-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helpdesk-service
  template:
    metadata:
      labels:
        app: helpdesk-service
      annotations:
        dynatrace.com/instrument: "true"
    spec:
      containers:
        - name: helpdesk-service
          image: 039612843833.dkr.ecr.us-east-1.amazonaws.com/enterprise-observability/helpdesk-service:v1.0.0
          ports:
            - containerPort: 8086
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: enterprise-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: enterprise-config
                  key: DB_PORT
            - name: DB_NAME
              value: "helpdesk_db"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: enterprise-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: enterprise-secrets
                  key: DB_PASSWORD
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: enterprise-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: enterprise-config
                  key: REDIS_PORT
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: enterprise-secrets
                  key: JWT_SECRET
            - name: DYNATRACE_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: enterprise-secrets
                  key: DYNATRACE_API_TOKEN
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8086
            initialDelaySeconds: 60
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8086
            initialDelaySeconds: 30
            periodSeconds: 10