---
apiVersion: v1
kind: Service
metadata:
  name: helpdesk-service
  namespace: enterprise-observability
  labels:
    app: helpdesk-service
spec:
  type: ClusterIP
  ports:
    - port: 8086
      targetPort: 8086
      protocol: TCP
  selector:
    app: helpdesk-service