---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-service
  namespace: enterprise-observability
  labels:
    app: authentication-service
    version: v1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-service
  template:
    metadata:
      labels:
        app: authentication-service
        version: v1.0.0
      annotations:
        dynatrace.com/instrument: "true"
    spec:
      containers:
        - name: authentication-service
          image: 039612843833.dkr.ecr.us-east-1.amazonaws.com/enterprise-observability/auth-service:v1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
              name: http
              protocol: TCP
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: enterprise-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: enterprise-config
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: enterprise-config
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: enterprise-secrets
                  key: DB_PASSWORD
            - name: DB_NAME
              value: "auth_db"
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: enterprise-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: enterprise-config
                  key: REDIS_PORT
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: enterprise-secrets
                  key: JWT_SECRET
          resources:
            requests:
              memory: "192Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3