---
apiVersion: v1
kind: Secret
metadata:
  name: dynatrace-secret
  namespace: dynatrace
  labels:
    app.kubernetes.io/managed-by: fluxcd
type: Opaque
stringData:
  DT_API_TOKEN: "your-dynatrace-api-token"
  DT_TENANT_URL: "https://your-tenant.dynatrace.com"