---
apiVersion: v1
kind: Service
metadata:
  name: payroll-service
  namespace: enterprise-observability
  labels:
    app: payroll-service
spec:
  type: ClusterIP
  ports:
    - port: 8084
      targetPort: 8084
      protocol: TCP
  selector:
    app: payroll-service