-- Salary profiles for the 100 seeded employees (employee_id matches employee-service sequential id 1-100)
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (1, 'Karan Reddy', 130000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (2, 'Harsh Das', 130000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (3, 'Myra Nair', 200000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (4, 'Reyansh Menon', 200000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (5, 'Seema Bhatt', 130000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (6, 'Shreya Joshi', 130000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (7, 'Sai Rao', 45000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (8, 'Divya Sharma', 100000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (9, 'Yash Bose', 100000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (10, 'Myra Chopra', 100000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (11, 'Ritu Saxena', 35000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (12, 'Siddharth Joshi', 60000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (13, 'Rohan Rao', 60000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (14, 'Sai Patel', 35000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (15, 'Rekha Kumar', 100000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (16, 'Ritu Verma', 80000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (17, 'Krishna Pandey', 80000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (18, 'Anita Mehta', 100000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (19, 'Meena Rao', 35000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (20, 'Varun Khan', 60000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (21, 'Rekha Khan', 35000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (22, 'Riya Chopra', 60000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (23, 'Suresh Kumar', 45000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (24, 'Riya Pillai', 35000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (25, 'Karan Iyer', 100000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (26, 'Anika Iyer', 80000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (27, 'Riya Pandey', 100000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (28, 'Nikhil Singh', 35000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (29, 'Swati Verma', 60000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (30, 'Riya Gupta', 45000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (31, 'Manisha Pillai', 60000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (32, 'Arjit Malhotra', 80000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (33, 'Ravi Nair', 60000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (34, 'Anika Naidu', 100000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (35, 'Kiara Naidu', 100000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (36, 'Seema Agarwal', 80000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (37, 'Pooja Malhotra', 35000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (38, 'Geeta Reddy', 45000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (39, 'Ananya Desai', 80000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (40, 'Arjun Patel', 80000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (41, 'Ravi Kapoor', 60000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (42, 'Geeta Sharma', 35000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (43, 'Manisha Bhatt', 60000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (44, 'Amit Reddy', 60000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (45, 'Ananya Chopra', 35000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (46, 'Manisha Naidu', 60000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (47, 'Gaurav Iyer', 100000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (48, 'Geeta Bose', 60000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (49, 'Pooja Chatterjee', 45000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (50, 'Suresh Shetty', 45000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (51, 'Tarun Pandey', 100000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (52, 'Divya Singh', 80000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (53, 'Suresh Mishra', 60000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (54, 'Vihaan Khan', 100000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (55, 'Sai Naidu', 80000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (56, 'Gaurav Bhatt', 45000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (57, 'Varun Malhotra', 100000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (58, 'Kiara Kapoor', 100000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (59, 'Saanvi Pandey', 100000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (60, 'Siddharth Rao', 60000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (61, 'Varun Bose', 60000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (62, 'Seema Kapoor', 80000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (63, 'Anika Khan', 35000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (64, 'Vivaan Agarwal', 100000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (65, 'Shreya Khan', 35000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (66, 'Arjun Mishra', 35000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (67, 'Arjun Kapoor', 45000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (68, 'Saanvi Bhatt', 45000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (69, 'Usha Mishra', 100000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (70, 'Priya Khan', 80000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (71, 'Aadhya Reddy', 35000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (72, 'Manoj Kumar', 80000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (73, 'Ravi Saxena', 35000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (74, 'Arjit Bose', 35000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (75, 'Sanjay Naidu', 60000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (76, 'Anika Rao', 45000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (77, 'Ashok Nair', 80000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (78, 'Anika Saxena', 35000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (79, 'Rekha Bhatt', 35000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (80, 'Arjit Bhatt', 35000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (81, 'Usha Shetty', 45000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (82, 'Deepak Malhotra', 80000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (83, 'Geeta Patel', 35000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (84, 'Rajesh Sharma', 80000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (85, 'Usha Desai', 80000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (86, 'Manoj Pillai', 100000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (87, 'Yash Malhotra', 45000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (88, 'Ira Rao', 35000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (89, 'Harsh Bhatt', 35000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (90, 'Rahul Verma', 35000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (91, 'Priya Kapoor', 100000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (92, 'Vihaan Kapoor', 35000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (93, 'Arjun Chatterjee', 35000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (94, 'Geeta Khan', 80000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (95, 'Manisha Agarwal', 45000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (96, 'Divya Verma', 100000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (97, 'Deepak Menon', 100000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (98, 'Sunita Singh', 60000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (99, 'Varun Pillai', 60000.00, TRUE);
INSERT INTO employee_salary_profiles (employee_id, employee_name, basic_salary, active) VALUES (100, 'Kiara Patel', 45000.00, TRUE);

-- Sample already-generated payroll records for a couple of past months (Jan/Feb 2026) for demo purposes
INSERT INTO payroll_records (employee_id, employee_name, pay_month, pay_year, basic_salary, bonus, gross_salary, tax_deducted, net_salary, status, generated_at) VALUES (1, 'Karan Reddy', 1, 2026, 130000.00, 6500.0, 136500.0, 14800.0, 121700.0, 'PAID', now() - interval '150 days');
INSERT INTO payroll_records (employee_id, employee_name, pay_month, pay_year, basic_salary, bonus, gross_salary, tax_deducted, net_salary, status, generated_at) VALUES (1, 'Karan Reddy', 2, 2026, 130000.00, 6500.0, 136500.0, 14800.0, 121700.0, 'PAID', now() - interval '120 days');
INSERT INTO payroll_records (employee_id, employee_name, pay_month, pay_year, basic_salary, bonus, gross_salary, tax_deducted, net_salary, status, generated_at) VALUES (2, 'Harsh Das', 1, 2026, 130000.00, 6500.0, 136500.0, 14800.0, 121700.0, 'PAID', now() - interval '150 days');
INSERT INTO payroll_records (employee_id, employee_name, pay_month, pay_year, basic_salary, bonus, gross_salary, tax_deducted, net_salary, status, generated_at) VALUES (2, 'Harsh Das', 2, 2026, 130000.00, 6500.0, 136500.0, 14800.0, 121700.0, 'PAID', now() - interval '120 days');
INSERT INTO payroll_records (employee_id, employee_name, pay_month, pay_year, basic_salary, bonus, gross_salary, tax_deducted, net_salary, status, generated_at) VALUES (3, 'Myra Nair', 1, 2026, 200000.00, 10000.0, 210000.0, 29500.0, 180500.0, 'PAID', now() - interval '150 days');
INSERT INTO payroll_records (employee_id, employee_name, pay_month, pay_year, basic_salary, bonus, gross_salary, tax_deducted, net_salary, status, generated_at) VALUES (3, 'Myra Nair', 2, 2026, 200000.00, 10000.0, 210000.0, 29500.0, 180500.0, 'PAID', now() - interval '120 days');
INSERT INTO payroll_records (employee_id, employee_name, pay_month, pay_year, basic_salary, bonus, gross_salary, tax_deducted, net_salary, status, generated_at) VALUES (7, 'Sai Rao', 1, 2026, 45000.00, 2250.0, 47250.0, 558.33, 46691.67, 'PAID', now() - interval '150 days');
INSERT INTO payroll_records (employee_id, employee_name, pay_month, pay_year, basic_salary, bonus, gross_salary, tax_deducted, net_salary, status, generated_at) VALUES (7, 'Sai Rao', 2, 2026, 45000.00, 2250.0, 47250.0, 558.33, 46691.67, 'PAID', now() - interval '120 days');
INSERT INTO payroll_records (employee_id, employee_name, pay_month, pay_year, basic_salary, bonus, gross_salary, tax_deducted, net_salary, status, generated_at) VALUES (8, 'Divya Sharma', 1, 2026, 100000.00, 5000.0, 105000.0, 8500.0, 96500.0, 'PAID', now() - interval '150 days');
INSERT INTO payroll_records (employee_id, employee_name, pay_month, pay_year, basic_salary, bonus, gross_salary, tax_deducted, net_salary, status, generated_at) VALUES (8, 'Divya Sharma', 2, 2026, 100000.00, 5000.0, 105000.0, 8500.0, 96500.0, 'PAID', now() - interval '120 days');
INSERT INTO payroll_records (employee_id, employee_name, pay_month, pay_year, basic_salary, bonus, gross_salary, tax_deducted, net_salary, status, generated_at) VALUES (9, 'Yash Bose', 1, 2026, 100000.00, 5000.0, 105000.0, 8500.0, 96500.0, 'PAID', now() - interval '150 days');
INSERT INTO payroll_records (employee_id, employee_name, pay_month, pay_year, basic_salary, bonus, gross_salary, tax_deducted, net_salary, status, generated_at) VALUES (9, 'Yash Bose', 2, 2026, 100000.00, 5000.0, 105000.0, 8500.0, 96500.0, 'PAID', now() - interval '120 days');
INSERT INTO payroll_records (employee_id, employee_name, pay_month, pay_year, basic_salary, bonus, gross_salary, tax_deducted, net_salary, status, generated_at) VALUES (10, 'Myra Chopra', 1, 2026, 100000.00, 5000.0, 105000.0, 8500.0, 96500.0, 'PAID', now() - interval '150 days');
INSERT INTO payroll_records (employee_id, employee_name, pay_month, pay_year, basic_salary, bonus, gross_salary, tax_deducted, net_salary, status, generated_at) VALUES (10, 'Myra Chopra', 2, 2026, 100000.00, 5000.0, 105000.0, 8500.0, 96500.0, 'PAID', now() - interval '120 days');
